# Dachshund Attacks

## Challenge Description

What if d is too small? Connect with nc mercury.picoctf.net 41508 

## Hint

What do you think about my pet? dachshund.jpg 

## Solution

I connected to the given address using netcat and got the following

```bash
~# nc mercury.picoctf.net 41508 
Welcome to my RSA challenge!
e: 46003015916643659896364356509258784680868533436739584309225802028304238414279787019332093773278626818135209492433608240967381673749491028525173442991664407616322169475988815494326048976666004207064391732259080778201821361318201759533111779948538576097527103577507750596053627701558501436130770848028965337059
n: 83084368459083414328041102040230255928495193899436230368111255161562690035761316867728506030308564003569820187420214487415962407873550819114217298176182772967785996025549469554824481066559532427502819167069786397005853113191499773875420360694730094763432255849026001595076599826649946700554309475617408505357
c: 40942227049976136710976360531372544246698546341806600929212410166244882707525301254584538578964155029483002305501888528924277435752039833086070770496373235112325175806418143947338029265343067776822018262555240757964132075689403713984018179920300040369543317269209534586132932340265474637662671756234343231261
```

Well it's clear that RSA encryption is being used. Now the challenge description says "What if d is too small?". Upon googling, I found out about *Wienerâ€™s attack*, which is a special kind of attack on RSA, that works only when the private key `d` is very small. The hint, which is an image of dachshund dog, also suggests this since they are also known as wiener dogs . Further googling led me to [this](https://github.com/orisano/owiener), a Python3 implementation of the Wiener attack . So after installing the module, I executed the following code

```bash
!pip install owiener
import owiener

e= 46003015916643659896364356509258784680868533436739584309225802028304238414279787019332093773278626818135209492433608240967381673749491028525173442991664407616322169475988815494326048976666004207064391732259080778201821361318201759533111779948538576097527103577507750596053627701558501436130770848028965337059
n= 83084368459083414328041102040230255928495193899436230368111255161562690035761316867728506030308564003569820187420214487415962407873550819114217298176182772967785996025549469554824481066559532427502819167069786397005853113191499773875420360694730094763432255849026001595076599826649946700554309475617408505357
c= 40942227049976136710976360531372544246698546341806600929212410166244882707525301254584538578964155029483002305501888528924277435752039833086070770496373235112325175806418143947338029265343067776822018262555240757964132075689403713984018179920300040369543317269209534586132932340265474637662671756234343231261
d = owiener.attack(e, n)

if d is None:
    print("Failed to recover d.")
else:
    print("Recovered d:", d)
   
    m = pow(c, d, n)
    print("Decrypted message:", m)
```
And I got the given output

```bash
Recovered d: 28753085762967182185932997077982374559319512118313596729529163151606863786739
Decrypted message: 198614235373674103788888306985643587194108045477674049828439424377979943293 
```

Further, I converted the long `m` to bytes

```bash
from Crypto.Util.number import long_to_bytes

plaintext = long_to_bytes(198614235373674103788888306985643587194108045477674049828439424377979943293)
print(plaintext.decode())
```

Upon execution, I got the flag

```bash
picoCTF{proving_wiener_3899149} 
```

Thus the flag for this challenge is `picoCTF{proving_wiener_3899149}`
